# Nombre del proyecto
name: ccl_app

# Descripción corta del proyecto
description: "A new Flutter project."

# Evita que se publique accidentalmente en pub.dev
publish_to: 'none'

# Versión de la app: major.minor.patch+build
version: 1.0.0+1

# SDK mínimo requerido
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Iconos estilo iOS
  cupertino_icons: ^1.0.8

  # Internacionalización fácil (traducciones)
  easy_localization: ^3.0.7+1

  # Navegación declarativa con generación de rutas
  auto_route: ^10.0.1

  # Inyección de dependencias (service locator)
  get_it: ^8.0.3

  # Complemento para get_it: generación automática
  injectable: ^2.5.0

  # Comparaciones por valor (ideal para estados)
  equatable: ^2.0.7

  # Manejo de estados con BLoC
  flutter_bloc: ^9.1.0

  # Programación funcional: Either, Option, etc.
  dartz: ^0.10.1

  # Pantalla de splash nativa automática
  flutter_native_splash: ^2.4.4

  # Acceso a rutas del sistema (documentos, etc.)
  path_provider: ^2.1.5

  # SQLite: base de datos local
  sqflite: ^2.4.1

  # Snackbars personalizados con contenido visual atractivo
  awesome_snackbar_content: ^0.1.5

  # Funciones de hash y seguridad (ej. para contraseñas)
  crypto: ^3.0.6

  # Framework de mocking para pruebas
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generador para auto_route
  auto_route_generator: ^10.0.1

  # Utilidades para pruebas de BLoC
  bloc_test: ^10.0.0

  # Motor de generación de código para injectable y auto_route
  build_runner:

  # Reglas de linting recomendadas por Flutter
  flutter_lints: ^5.0.0

  # Generador para injectable
  injectable_generator:

flutter:
  # Usa el conjunto de íconos Material
  uses-material-design: true

  # Recursos de imágenes y base de datos
  assets:
    - assets/images/
    - assets/database/

  # (Opcional) Puedes agregar fuentes personalizadas aquí.
  # fonts:
  #   - family: MiFuente
  #     fonts:
  #       - asset: fonts/MiFuente-Regular.ttf
