# Project name
name: ccl_app

# Short project description
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# App version: major.minor.patch+build
version: 1.0.0+1

# Minimum required Dart SDK
environment:
  sdk: ^3.6.0

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # Easy localization and translation support
  easy_localization: ^3.0.7+1

  # Declarative navigation with automatic route generation
  auto_route: ^10.0.1

  # Dependency injection service locator
  get_it: ^8.0.3

  # Extension for get_it that enables code generation
  injectable: ^2.5.0

  # Value-based equality (ideal for state classes)
  equatable: ^2.0.7

  # State management using the BLoC pattern
  flutter_bloc: ^9.1.0

  # Functional programming tools like Either and Option
  dartz: ^0.10.1

  # Auto splash screen generation for Android and iOS
  flutter_native_splash: ^2.4.4

  # File system path utilities (e.g. documents directory)
  path_provider: ^2.1.5

  # SQLite: local persistent storage
  sqflite: ^2.4.1

  # Custom and visually styled snackbars
  awesome_snackbar_content: ^0.1.5

  # Cryptographic utilities (e.g. SHA256 for password hashing)
  crypto: ^3.0.6

  # Mocking framework for unit/widget testing
  mocktail: ^1.0.4

dev_dependencies:
  # Flutter's built-in testing library
  flutter_test:
    sdk: flutter

  # Route generator for auto_route
  auto_route_generator: ^10.0.1

  # Tools for testing BLoC logic
  bloc_test: ^10.0.0

  # Code generation engine used by auto_route and injectable
  build_runner:

  # Flutter's recommended linter rules
  flutter_lints: ^5.0.0

  # Generator for injectable dependencies
  injectable_generator:

flutter:
  # Use Material Design icon set
  uses-material-design: true

  # Declare asset folders
  assets:
    - assets/images/     # Images (e.g. logo)
    - assets/database/   # Preloaded or local database files

  # (Optional) You can register custom fonts here.
  # fonts:
  #   - family: MyFont
  #     fonts:
  #       - asset: fonts/MyFont-Regular.ttf
